four_year_plan/urls.py
from django.urls import include, re_path, path

from planner.views import profile

from django.contrib import admin

admin.autodiscover()

urlpatterns = [
    re_path(r'^$', profile),
    re_path(r'planner/', include('planner.urls')),

    re_path(r'accounts/', include('django.contrib.auth.urls')),

    re_path(r'admin/doc/', include('django.contrib.admindocs.urls')),
    path(r'admin/', admin.site.urls),
]

planner/urls.py
from django.urls import re_path, path, include

from . import views
#from planner.views import profile

urlpatterns = [

    path(r'home/', views.home),
    path(r'register/', views.student_registration, name='planner.views.register'),
    path(r'profile/', views.profile, name='planner.views.profile'),

    re_path(r'^changemajor/(\d+)/$', views.update_major, name='planner.views.update_major'),
    re_path(r'^updatesemester/(\d+)/$', views.update_student_semester, name='planner.views.update_student_semester'),
    re_path(r'^fouryearplan/$', views.display_four_year_plan, name='planner.views.display_four_year_plan'),
    re_path(r'^graduationaudit/$', views.display_grad_audit, name='planner.views.display_grad_audit'),

    re_path(r'^advisingnotes/', views.display_advising_notes, name='planner.views.display_advising_notes'),
    re_path(r'^addadvisingnote/', views.add_new_advising_note, name='planner.views.add_new_note'),
    re_path(r'^updateNote/(\d+)/$', views.update_advising_note, name='planner.views.update_note'),
    re_path(r'^deleteNote/(\d+)/$', views.delete_advising_note, name='planner.views.delete_note'),

    re_path(r'^addcreateyourowncourse/(\d+)/$', views.add_create_your_own_course, name='planner.views.add_cyoc'),
    re_path(r'^deletecyoc/(\d+)/(\d+)/(\d+)/$', views.delete_create_your_own_course, name='planner.views.delete_cyoc'),
    re_path(r'^updatecyoc/(\d+)/(\d+)/$', views.update_create_your_own_course, name='planner.views.update_cyoc'),

    re_path(r'^deletecourse/(\d+)/(\d+)/(\d+)/$', views.delete_course_inside_SSCObject, name='planner.views.delete_course'),
    re_path(r'^movecoursetonewsemester/(\d+)/(-?\d+)/(\d+)/(\d+)/$', views.move_course_to_new_SSCObject, name='planner.views.move_course'),

    re_path(r'^changeadvisee/(\d+)/$', views.update_advisee, name='planner.views.update_advisee'),
    re_path(r'^search/$', views.search, name='planner.views.search'),
    re_path(r'^viewstudents/(\d+)/(\d+)/$', views.view_enrolled_students, name='planner.views.view_students'),


]

planner/models.py
from django.db import models
from django.forms import ModelForm
from django.db.models.signals import post_save
from django.contrib.auth.models import User
from django.db.models import Sum

# here's how to extract all courses for a given semester:
# from django.db.models import Q
# jterm_course_list = Course.objects.filter(Q(semester__actual_year="2013") & Q(semester__semester_of_acad_year = 1))
# for courses in jterm_course_list:
#    print courses.id
#
# information on having a user login, including a emplate and login stuff:
# https://docs.djangoproject.com/en/dev/topics/auth/
#
# the following might help, too:
# http://stackoverflow.com/questions/7133455/django-limit-choices-to-doesnt-work-on-manytomanyfield
#
# also, here: https://docs.djangoproject.com/en/dev/ref/models/fields/
#

class Semester(models.Model):
    FALL_SEMESTER = 1
    JTERM_SEMESTER = 2
    SPRING_SEMESTER = 3
    SUMMER_SEMESTER = 4
    SEMESTER_CHOICES = (
        (FALL_SEMESTER, 'Fall'),
        (JTERM_SEMESTER, 'J-term'),
        (SPRING_SEMESTER, 'Spring'),
        (SUMMER_SEMESTER, 'Summer'),
    )

    Y2009 = 2009
    Y2010 = 2010
    Y2011 = 2011
    Y2012 = 2012
    Y2013 = 2013
    Y2014 = 2014
    Y2015 = 2015
    Y2016 = 2016
    Y2017 = 2017
    Y2018 = 2018
    Y2019 = 2019
    Y2020 = 2020
    Y2021 = 2021
    Y2022 = 2022
    Y2023 = 2023
    Y2024 = 2024
    Y2025 = 2025
    Y2026 = 2026
    Y2027 = 2027
    Y2028 = 2028
    Y2029 = 2029
    Y2030 = 2030
    

    YEAR_CHOICES = (
        (Y2009, '2009'),
        (Y2010, '2010'),
        (Y2011, '2011'),
        (Y2012, '2012'),
        (Y2013, '2013'),
        (Y2014, '2014'),
        (Y2015, '2015'),
        (Y2016, '2016'),
        (Y2017, '2017'),
        (Y2018, '2018'),
        (Y2019, '2019'),
        (Y2020, '2020'),
        (Y2021, '2021'),
        (Y2022, '2022'),
        (Y2023, '2023'),
        (Y2024, '2024'),
        (Y2025, '2025'),
        (Y2026, '2026'),
        (Y2027, '2027'),
        (Y2028, '2028'),
        (Y2029, '2029'),
        (Y2030, '2030'),        
    )

    name = models.CharField(max_length=50,help_text="e.g., Fa18 or J19")
    semester_of_acad_year = models.IntegerField(choices=SEMESTER_CHOICES, default = FALL_SEMESTER)
    actual_year = models.PositiveIntegerField(choices=YEAR_CHOICES, default = Y2018)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['semester_of_acad_year']


class Department(models.Model):
    name = models.CharField(max_length=50, help_text="e.g., Physics and Engineering")

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']

class Course(models.Model):

    cr0 = 0
    cr1 = 1
    cr2 = 2
    cr3 = 3
    cr4 = 4
    cr5 = 5
    cr6 = 6

    CREDIT_CHOICES = (
        (cr0, '0'),
        (cr1, '1'),
        (cr2, '2'),
        (cr3, '3'),
        (cr4, '4'),
        (cr5, '5'),
        (cr6, '6'),
    )

    name = models.CharField(max_length=50,help_text="e.g., University Physics I & Lab")
    number = models.CharField(max_length=10, help_text="e.g., PHY211")
    department = models.ForeignKey(Department, on_delete=models.PROTECT)
    credit_hours = models.PositiveIntegerField(choices = CREDIT_CHOICES, default=cr3)
    semester = models.ManyToManyField(Semester)
    prereqs = models.ManyToManyField("self", symmetrical = False,
                                     related_name='pre_courses', blank=True)
    coreqs = models.ManyToManyField("self", symmetrical = False,
                                    related_name='co_courses', blank=True)
    sp = models.BooleanField(default = False, verbose_name="SP")
    cc = models.BooleanField(default = False, verbose_name="CC")

    def __str__(self):
        return self.number

    class Meta:
        ordering = ['number']

class RequirementBlock(models.Model):
    ANDREQ = 1
    ORREQ = 2
    AND_OR_CHOICES = (
        (ANDREQ, 'AND'),
        (ORREQ, 'OR')
    )

    name = models.CharField(max_length=50, help_text="e.g., PhysicsBS Technical Electives, or GenEd Literature; first part is helpful for searching (when creating a major).")
    display_name = models.CharField(max_length=50, help_text="e.g., Technical Electives, or Literature; this is the title that will show up when students do a graduation audit.")

    AND_or_OR_Requirement = models.IntegerField(choices=AND_OR_CHOICES, default = ANDREQ,
                                                help_text = "Choose AND if all are required, OR if a subset is required.")
    minimum_number_of_credit_hours = models.IntegerField(default = 10)
    list_order = models.PositiveIntegerField(default = 1, help_text="Preferred place in the list of requirements; it is OK if numbers are repeated or skipped.")
    # This will be used to order the requirements when viewed by the user.
    text_for_user = models.CharField(max_length=200, blank = True, help_text="Optional helpful text for the user; will appear in the graduation audit.")
    courselist = models.ManyToManyField(Course, help_text = "Select courses for this requirement.")


    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']


class Major(models.Model):

    name = models.CharField(max_length=50,
                            help_text="e.g., Physics BS or Mathematics BA.")
    major_requirements = models.ManyToManyField(RequirementBlock)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']

class UserProxy(User):
    class Meta:
        proxy = True

    def __str__(self):
        return self.get_full_name()

    def info(self):
        info = [ "id '{0}'".format(self.get_username()) ]
        if self.is_student():
            info.append('student')
        if self.is_professor():
            info.append('professor')
        return ", ".join(info)

    def is_student(self):
        try:
            if self.student:
                return True
        except Student.DoesNotExist:
            return False

    def get_student_id(self):
        assert(self.is_student())
        return self.student.id

    def is_professor(self):
        try:
            if self.professor:
                return True
        except Professor.DoesNotExist:
            return False

    def get_professor_id(self):
        assert(self.is_professor())
        return self.professor.id

from django.contrib.auth.backends import ModelBackend
class ProxiedModelBackend(ModelBackend):
    def get_user(self, user_id):
        try:
            return UserProxy.objects.get(pk=user_id)
        except UserProxy.DoesNotExist:
            return None

class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.PROTECT)
    name = models.CharField(max_length=100)
    major = models.ForeignKey(Major, blank=True, null=True, on_delete=models.PROTECT)
    entering_year = models.PositiveIntegerField(default=2018, help_text = "e.g., 2018")
    # might need to add null=True above as well....
    #    birthday = models.DateField(blank=True, null=True)
    # Update 5/9/2013 - Items to add
    # current_status = models.CharField(max_length=100) Freshman - Senior For display purposes

    def __str__(self):
        return self.name

    def num_credit_hours(self, student_semester_course):
        credit_hours = student_semester_course.courses.aggregate(Sum('credit_hours'))
        credit_hours = credit_hours['credit_hours__sum']
        credit_hours = 0 if credit_hours is None else credit_hours

        cyo_courses = CreateYourOwnCourse.objects.filter(student=self, semester=student_semester_course.semester, actual_year=student_semester_course.actual_year)
        cyo_courses = CreateYourOwnCourse.objects.filter(student=self, semester=student_semester_course.semester)
        cyo_courses = cyo_courses.filter(actual_year=student_semester_course.actual_year)
        cyo_courses_hours = cyo_courses.aggregate(Sum('credit_hours'))['credit_hours__sum']
        cyo_courses_hours = 0 if cyo_courses_hours is None else cyo_courses_hours
        return credit_hours + cyo_courses_hours

    class Meta:
        ordering = ['name']


class Professor(models.Model):
    user = models.OneToOneField(User, on_delete=models.PROTECT)
    name = models.CharField(max_length=100)
    advisee = models.ForeignKey(Student, blank=True, null=True, on_delete=models.PROTECT)

    def __str__(self):
        return self.name

class StudentSemesterCourses(models.Model):
    PRETU_SEMESTER = 0
    FALL_SEMESTER = 1
    JTERM_SEMESTER = 2
    SPRING_SEMESTER = 3
    SUMMER_SEMESTER = 4
    SEMESTER_CHOICES = (
        (PRETU_SEMESTER, 'Pre-TU'),
        (FALL_SEMESTER, 'Fall'),
        (JTERM_SEMESTER, 'J-term'),
        (SPRING_SEMESTER, 'Spring'),
        (SUMMER_SEMESTER, 'Summer'),
    )

    PRETU_YEAR = 0
    FRESHMAN_YEAR = 1
    SOPHMORE_YEAR = 2
    JUNIOR_YEAR = 3
    SENIOR_YEAR = 4
    SUPERSENIOR_YEAR = 5
    YEAR_CHOICES = (
        (PRETU_YEAR, 'Pre-TU'),
        (FRESHMAN_YEAR, 'Freshman'),
        (SOPHMORE_YEAR, 'Sophmore'),
        (JUNIOR_YEAR, 'Junior'),
        (SENIOR_YEAR, 'Senior'),
        (SUPERSENIOR_YEAR, 'Super-Senior'),
    )

    semester = models.PositiveIntegerField(choices=SEMESTER_CHOICES, default = FALL_SEMESTER)
    year = models.PositiveIntegerField(choices=YEAR_CHOICES, default = FRESHMAN_YEAR)
    student = models.ForeignKey(Student, related_name='ssc_student', on_delete=models.PROTECT)
    courses = models.ManyToManyField(Course, related_name='semestercourses', blank=True)
    #    actual_year=models.PositiveIntegerField(default='2012')

    class Meta:
        verbose_name_plural = 'Student semester courses'

    def __str__(self):
        return "{0} {1} {2}".format(self.student,
                                    self.get_year_display(),
                                    self.get_semester_display())


    @property
    def actual_year(self):
        if self.semester == 1:
            return self.student.entering_year + self.year - 1

planner/forms.py
from django import forms
from django.contrib.auth.models import User
from django.db.models import Q
from .models import *

class RegistrationForm(forms.ModelForm):
    username = forms.CharField(label=(u'User Name'))
    email = forms.EmailField(label=(u'Email Address'))
    password = forms.CharField(label=(u'Password'),
                               widget=forms.PasswordInput(render_value=False))
    password1 = forms.CharField(label=(u'Verify Password'),
                                widget=forms.PasswordInput(render_value=False))

    class Meta:
        model = Student
        exclude = ('user',)

    def clean_username(self):
        username = self.cleaned_data['username']
        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username
        raise forms.ValidationError("That username is already taken; please select another.")

    def clean(self):
        password = self.cleaned_data.get('password')
        password1 = self.cleaned_data.get('password1')
        if password and password1 and password != password1:
            raise forms.ValidationError("The passwords did not match.  Please try again.")

        # something seems to be wrong here -- it doesn't associate the error with
        # password; it does throw the exception, I think (i.e., it returns an error), but
        # it doesn't specifically give the password error message....
        return self.cleaned_data

class AddStudentSemesterForm(forms.ModelForm):
    class Meta:
        model = StudentSemesterCourses
        exclude = ('semester','year','student')

    def __init__(self, *args, **kwargs):
        actyear = kwargs.pop('actual_year')
        sem = kwargs.pop('semester')
        super (AddStudentSemesterForm,self).__init__(*args,**kwargs)
        if sem == 0:
            self.fields['courses'].queryset = Course.objects.all()
        else:
            self.fields['courses'].queryset = Course.objects.filter(Q(semester__actual_year=actyear) 
                                                                    & Q(semester__semester_of_acad_year = sem))

    def clean_student(self):
        courses = self.cleaned_data['courses']
        return courses

class AddAdvisingNoteForm(forms.ModelForm):

    class Meta:
        model = AdvisingNote
        exclude = ('student', 'datestamp')

class AddCreateYourOwnCourseForm(forms.ModelForm):

    class Meta:
        model = CreateYourOwnCourse
        exclude = ('semester', 'actual_year', 'student')

class AddAdviseeForm(forms.ModelForm):

    class Meta:
        model = Professor
        exclude = ('user', 'name')

    def __init__(self, *args, **kwargs):
        super (AddAdviseeForm, self).__init__(*args, **kwargs)
        self.fields['advisee'].queryset = Student.objects.filter(user__is_active = True)

        
class UpdateMajorForm(forms.ModelForm):

    class Meta:
        model = Student
        exclude = ('user', 'name', 'entering_year')

planner/templates/addAdvisingNote.html
{% extends "base.html" %}

{% block content %}

 <div class="content-center">
    <form method="post">
      {% csrf_token %} {% if form.errors %}

      <p>Please correct the following fields:</p>{% endif %}

      <div class="addNote_div">
        {% if form.note.errors %}

        <p class="error">{{ form.note.errors }}</p>{% endif %}

        <p><label form="courses" if="" form.note.errors="" class="error" endif=
        "">Note:</label></p>

        <p>{{ form.note }}</p>
      </div>

      <p><input type="submit" alt="register" class="submitButton"/></p>
    </form>
  </div>

  <script>
    $(window).load(function(){
    $("#nav-notes").addClass("current");
    $('.page-name').find('h1').replaceWith('<h1>Add Advising Note</h1>');
    $(".page-name").stop().animate({opacity: 1,'margin-left': '5%'}, 700);});
  </script>
{% endblock %}

planner/templates/addadvisee.html
{% extends "base.html" %}

{% block content %}

<div class="content-center">
    <form action="" method="post">
      {% csrf_token %} {% if form.errors %}

      <p>Please correct the following fields:</p>{% endif %}

      <div class="addAdv_div">
        {% if form.advisee.errors %}

        <p class="error">{{ form.advisee.errors }}</p>{% endif %}

        <p><label form="advisee" if="" form.advisee.errors="" class="error" endif=
        "">Choose advisee:</label></p>

        <p>{{ form.advisee }}</p>
      </div>

      <p><input type="submit" alt="register" class="submitButton" /></p>
    </form>
  </div>

  <script>
    $(window).load(function(){
    $("#nav-plan").addClass("current");
    $('.page-name').find('h1').replaceWith('<h1>Add Advisee</h1>');
    $(".page-name").stop().animate({opacity: 1,'margin-left': '5%'}, 700);});
  </script>

{% endblock %}

planner/templates/advisingnotes.html
{% extends "base.html" %}

{% block sidebar %}
  <div class="alert alert-student-info">
  {% if isProfessor %}
    <p>
      Advisee Name: {{ student.name }} (<a href="{% url 'planner.views.update_advisee' 3 %}">Change</a>)
    </p>
  {% else %}
    <p>Name: {{ student.name }}</p>
  {% endif %}

  <p>Email: {{ student.user.email }}</p>
  <p>Major: {{ student.major }}</p>
  <p>Entering Year: {{ student.entering_year }}</p>
  </div>
{% endblock %}

{% block content %}
  <table class="table table-striped table-bordered table-hover">
    <tbody>
      {% for item in datablock %}
	<tr class="info">
	  <td>{{ item.3 }}</td>
	  <td>{{ item.0 }}</td>
	  {% if not isProfessor %}
	    <td>
	      <a class="btn" href="{% url 'planner.views.update_note' item.2 %}">Edit</a>
	      <a class="btn btn-danger" href="{% url 'planner.views.delete_note' item.2 %}">Delete</a>
	    </td>
	  {% endif %}
	</tr>
        <tr>
	  <td colspan="3">
	    {{ item.1 }}
	  </td>
	</tr>
      {% endfor %}
    </tbody>
  </table>

  {% if not isProfessor %}
    <p>
      <a class="btn btn-primary" href="{% url 'planner.views.add_new_note' %}">Add a Note</a>
    </p>
  {% endif %}
  <script>
    $(window).load(function(){
    $("#nav-notes").addClass("current");
    $('.page-name').find('h1').replaceWith('<h1>Advising Note</h1>');
    $(".page-name").stop().animate({opacity: 1,'margin-left': '5%'}, 700);});
  </script>

{% endblock %}

planner/templates/choosecourse.html
{% extends "base.html" %}
{% block extrahead %}
{% endblock %}
{% block content %}
<form action="/search/" method="get">
        <input type="text" name="q">
        <input type="submit" value="Search" class="submitButton">
</form>
{% endblock %}

planner/templates/course_enrollment_results.html
{% extends "base.html" %}

{% block content %}
 <div class="content-center">
  <p>
    You searched for: <strong>{{ query }}</strong>
  </p>
  <form action="{% url 'planner.views.search' %}" method="get">
      <input type="text" name="q" placeholder="Search Again"><br>
      <input type="submit" value="Search" >
  </form>
  {% if courses %}
   <table class="table table-striped table-bordered table-hover">
      <tbody>
	<tr>
    <p>
      Found {{ courses|length }} course{{ courses|pluralize }}.
    </p>
      {% for course in datablock %}

	<li>{{course.1}} ({{course.2}})

	   <table class="table table-striped table-bordered table-hover">
	     <thead>
	       <tr>
		<th>Semester</th>
		<th># of Students</th>
	       </tr>
	     </thead>
	     <tbody>

            {% for actsem in course.3 %}
		
	       <tr>
		<td><a class="btn" href="{% url 'planner.views.view_students' course.0 actsem.2 %}">{{ actsem.0 }}</a></td>
		<td>{{ actsem.1 }} student{{actsem.1|pluralize}}</td>
	       </tr>
		
	    {% endfor %}

	    </tbody>
	  </table>
      {% endfor %}

  {% else %}
    <p>No courses matched your search criteria.</p>
  {% endif %}

{% endblock %}
</div>

planner/templates/home.html
{% extends "base.html" %}

{% block content %}
<div>
  <p>Thank you for visiting our website.</p>
</div>
{% endblock %}

planner/templates/login.html
{% extends "base.html" %}

{% block content %}
  <div class="content-center">
  <h1>Current Users</h1>
  <form action="" method="post">
    {% csrf_token %}
    {% if form.errors %}<p>Please correct the following fields:</p>{% endif %}

    <div class="register_div">
      {% if form.username.errors %}
	<p class = "error">{{ form.username.errors }}</p>
      {% endif %}

      <p>
	<label form="username" {% if form.username.errors %} class ="error"{% endif %}>Student ID (e.g., @00551111):</label></p>
      <p>{{ form.username }}</p>
    </div>

    <div class="register_div">
      {% if form.password.errors %}<p class = "error">{{ form.password.errors }}</p>{% endif %}
      <p><label form="password" {% if form.password.errors %} class ="error"{% endif %}>Password:</label></p>
      <p>{{ form.password }}</p>
    </div>

    <p><input type="submit" alt="register" /></p>
  </form>
<p>Forgot your password? <a href="/resetpassword/">Reset it!</a></p>

<h1>New Users</h1>
<p><a href="{% url 'planner.views.register' %}">Sign up!</a></p>
</div>
<script>
$(window).load(function(){
$("#nav-login").addClass("current");
$('.page-name').find('h1').replaceWith('<h1>Login</h1>');
$(".page-name").stop().animate({
                opacity: 1,
	        'margin-left': '5%'
            }, 700);});
</script>
{% endblock %}

planner/templates/student_enrollment_results.html
{% extends "base.html" %}
{% block extrahead %}
{% endblock %}
{% block content %}
 <div class="content-center">
<p> The following students are enrolled in {{coursename}} for {{semestername}}:</p>
<table class="table table-striped table-bordered table-hover">
	     <thead>
	       <tr>
		<th>Student</th>
	       </tr>
	     </thead>
	     <tbody>
{% for student in studentlist %}
    <tr><td> {{student}}</tr></td>
{% endfor %}
</table>
<FORM><INPUT Type="button" class="submitButton" VALUE="Back" onClick="history.go(-1);return true;"></FORM>
</div>
{% endblock %}

planner/templates/temphold.html
<!--
<p>You searched for: <strong>{{ query }}</strong></p>

{% if courses %}
    <p>Found {{ courses|length }} course{{ courses|pluralize }}.</p>
    <ul>
        {% for course in courses %}
        <li>{{ course.name }}</li>
        {% endfor %}
    </ul>
{% else %}
    <p>No courses matched your search criteria.</p>
{% endif %}
{% endblock %}
-->

planner/templates/updatePreTUCourses.html
{% extends "base.html" %}
{% block extrahead %}
{% endblock %}
{% block content %}
<form action="" method="post">
{% csrf_token %}
{% if form.errors %}<p>Please correct the following fields:</p>{% endif %}
<div class="updatePreTU_div">
  {% if form.courses.errors %}<p class = "error">{{ form.courses.errors }}</p>{% endif %}
  <p><label form="courses" {% if form.courses.errors %} class ="error"{% endif %}>Courses:</label></p>
  <p>{{ form.courses }}</p>
</div>
<p><input type="submit" alt="register" class="submitButton"/></p>
</form>
{% endblock %}

planner/templates/updatesemester.html
{% extends "base.html" %}

{% load static %}

{% block extrahead %}
  <link href="{% static 'css/chosen.css' %}" media="screen" rel="stylesheet" type="text/css">
  <script src="http://code.jquery.com/jquery-1.9.0.min.js"></script>
  <script src="http://code.jquery.com/ui/1.9.2/jquery-ui.min.js"></script>
{% endblock %}

{% block content %}
  <div class="content-center">
  <h1>Standard Courses</h1>

  <form action="" method="post">
    {% csrf_token %}
    {% if form.errors %}
      <p>Please correct the following fields:</p>
    {% endif %}

    <div class="updatesemester_div">
      {% if form.courses.errors %}
	<p class = "error">{{ form.courses.errors }}</p>
      {% endif %}
      <p><label form="courses" {% if form.courses.errors %} class ="error"{% endif %}>Courses:</label></p>

      <p>Select a course to add to your four-year plan.</p>
      <span>{{ form.courses }}</span>
    </div>
    <div class="alert alert-student-info">  
  	<a class="close" data-dismiss="alert">×</a>  
 	 <strong>Hint:</strong> Start typing in the course search bar or click 			and use the dropdown.  
    </div>  
    <p>
      <input type="submit" alt="register" value="Submit Courses" />
    </p>
  </form>
  

  <h1>Create Your Own Course</h1>

  <p>
    If a standard course doesn't fit your graduation requirements,
    you can create your own course.
    Here are some situations in which you should create your own course:
    <ul>
      <li>
	You transferred, or plan to transfer, this course in from another institution.
      </li>
      <li>
	A course is offered during the present semester,
	but doesn't appear in the standard course list.
      </li>
    </ul>
  </p>

  <p><strong>List of "create your own" type courses for the present semester:</strong>
    <ul>
      {% for course in sccdatablock %}
	<li>
	  {{course.cname}}
	  ({{course.cnumber}},
	  {{course.ccredithrs}} hrs{{course.equivalentcourse}}{{course.sp}}{{course.cc}})
	  (<a class="other" href="{% url 'planner.views.update_cyoc' instanceid course.courseid %}">Edit</a>,
	   <a class="other" href="{% url 'planner.views.delete_cyoc' 2 instanceid course.courseid %}">Delete</a>)
	</li>
      {% empty %}
	<li>None</li>
      {% endfor %}
    </ul>
  </p>

  <p>To add a new "create your own" type course,
    <a class="other" href="{% url 'planner.views.add_cyoc' instanceid %}">click here</a>.
  </p>

  </form>
  </div>

   <script src="{% static 'js/chosen.jquery.js' %}" type="text/javascript"></script>
  <script type="text/javascript"> $("#id_courses").chosen(); $(".chzn-select-deselect").chosen({allow_single_deselect:true}); </script>
  <script type="text/javascript">
              $(document).ready(function () {
                $(".alert").alert()
                });
  </script>
  <script>
    $(window).load(function(){
    $("#nav-plan").addClass("current");
    $('.page-name').find('h1').replaceWith('<h1>Update Semester</h1>');
    $(".page-name").stop().animate({opacity: 1,'margin-left': '5%'}, 700);});
  </script>
{% endblock %}